# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', ckeditor.fields.RichTextField()),
                ('task_text', ckeditor.fields.RichTextField()),
                ('date_published', models.DateField()),
                ('slug', models.SlugField(default='lesson')),
            ],
        ),
    ]
