# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_title', models.CharField(max_length=200)),
                ('theory_text', models.TextField()),
                ('theory_date', models.DateField()),
            ],
            options={
                'db_table': 'theory',
            },
        ),
    ]
