# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='theory_slug',
            field=models.SlugField(default='default'),
        ),
    ]
