# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 15:32
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0002_theory_theory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='theory_text',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
