# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0004_auto_20160515_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='theory_slug',
        ),
    ]
