# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 12:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0005_remove_theory_theory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='theory_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
