# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0006_auto_20160516_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='theory_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
