# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkr', '0007_auto_20160516_2001'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='theory',
            table='Теория',
        ),
    ]
